Error: uncaught exception... error(type_error(callable,1))
